# CMake generated Testfile for 
# Source directory: /home/serboba/transferompl_ws/src/ompl_iso/tests
# Build directory: /home/serboba/transferompl_ws/src/ompl_iso/demos/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_adjacency_list "/home/serboba/transferompl_ws/src/ompl_iso/demos/tests/test_adjacency_list")
set_tests_properties(test_adjacency_list PROPERTIES  _BACKTRACE_TRIPLES "/home/serboba/transferompl_ws/src/ompl_iso/CMakeModules/OMPLUtils.cmake;8;add_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;16;add_ompl_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;0;")
add_test(test_heap "/home/serboba/transferompl_ws/src/ompl_iso/demos/tests/test_heap")
set_tests_properties(test_heap PROPERTIES  _BACKTRACE_TRIPLES "/home/serboba/transferompl_ws/src/ompl_iso/CMakeModules/OMPLUtils.cmake;8;add_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;17;add_ompl_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;0;")
add_test(test_grid "/home/serboba/transferompl_ws/src/ompl_iso/demos/tests/test_grid")
set_tests_properties(test_grid PROPERTIES  _BACKTRACE_TRIPLES "/home/serboba/transferompl_ws/src/ompl_iso/CMakeModules/OMPLUtils.cmake;8;add_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;20;add_ompl_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;0;")
add_test(test_gridb "/home/serboba/transferompl_ws/src/ompl_iso/demos/tests/test_gridb")
set_tests_properties(test_gridb PROPERTIES  _BACKTRACE_TRIPLES "/home/serboba/transferompl_ws/src/ompl_iso/CMakeModules/OMPLUtils.cmake;8;add_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;21;add_ompl_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;0;")
add_test(test_nearestneighbors "/home/serboba/transferompl_ws/src/ompl_iso/demos/tests/test_nearestneighbors")
set_tests_properties(test_nearestneighbors PROPERTIES  _BACKTRACE_TRIPLES "/home/serboba/transferompl_ws/src/ompl_iso/CMakeModules/OMPLUtils.cmake;8;add_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;22;add_ompl_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;0;")
add_test(test_pdf "/home/serboba/transferompl_ws/src/ompl_iso/demos/tests/test_pdf")
set_tests_properties(test_pdf PROPERTIES  _BACKTRACE_TRIPLES "/home/serboba/transferompl_ws/src/ompl_iso/CMakeModules/OMPLUtils.cmake;8;add_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;30;add_ompl_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;0;")
add_test(test_random "/home/serboba/transferompl_ws/src/ompl_iso/demos/tests/test_random")
set_tests_properties(test_random PROPERTIES  _BACKTRACE_TRIPLES "/home/serboba/transferompl_ws/src/ompl_iso/CMakeModules/OMPLUtils.cmake;8;add_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;33;add_ompl_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;0;")
add_test(test_halton_sampling "/home/serboba/transferompl_ws/src/ompl_iso/demos/tests/test_halton_sampling")
set_tests_properties(test_halton_sampling PROPERTIES  _BACKTRACE_TRIPLES "/home/serboba/transferompl_ws/src/ompl_iso/CMakeModules/OMPLUtils.cmake;8;add_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;40;add_ompl_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;0;")
add_test(test_state_operations "/home/serboba/transferompl_ws/src/ompl_iso/demos/tests/test_state_operations")
set_tests_properties(test_state_operations PROPERTIES  _BACKTRACE_TRIPLES "/home/serboba/transferompl_ws/src/ompl_iso/CMakeModules/OMPLUtils.cmake;8;add_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;41;add_ompl_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;0;")
add_test(test_state_spaces "/home/serboba/transferompl_ws/src/ompl_iso/demos/tests/test_state_spaces")
set_tests_properties(test_state_spaces PROPERTIES  _BACKTRACE_TRIPLES "/home/serboba/transferompl_ws/src/ompl_iso/CMakeModules/OMPLUtils.cmake;8;add_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;42;add_ompl_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;0;")
add_test(test_state_storage "/home/serboba/transferompl_ws/src/ompl_iso/demos/tests/test_state_storage")
set_tests_properties(test_state_storage PROPERTIES  _BACKTRACE_TRIPLES "/home/serboba/transferompl_ws/src/ompl_iso/CMakeModules/OMPLUtils.cmake;8;add_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;43;add_ompl_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;0;")
add_test(test_planner_data "/home/serboba/transferompl_ws/src/ompl_iso/demos/tests/test_planner_data")
set_tests_properties(test_planner_data PROPERTIES  _BACKTRACE_TRIPLES "/home/serboba/transferompl_ws/src/ompl_iso/CMakeModules/OMPLUtils.cmake;8;add_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;44;add_ompl_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;0;")
add_test(test_ptc "/home/serboba/transferompl_ws/src/ompl_iso/demos/tests/test_ptc")
set_tests_properties(test_ptc PROPERTIES  _BACKTRACE_TRIPLES "/home/serboba/transferompl_ws/src/ompl_iso/CMakeModules/OMPLUtils.cmake;8;add_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;47;add_ompl_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;0;")
add_test(test_2dmap_geometric_simple "/home/serboba/transferompl_ws/src/ompl_iso/demos/tests/test_2dmap_geometric_simple")
set_tests_properties(test_2dmap_geometric_simple PROPERTIES  _BACKTRACE_TRIPLES "/home/serboba/transferompl_ws/src/ompl_iso/CMakeModules/OMPLUtils.cmake;8;add_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;52;add_ompl_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;0;")
add_test(test_2dmap_ik "/home/serboba/transferompl_ws/src/ompl_iso/demos/tests/test_2dmap_ik")
set_tests_properties(test_2dmap_ik PROPERTIES  _BACKTRACE_TRIPLES "/home/serboba/transferompl_ws/src/ompl_iso/CMakeModules/OMPLUtils.cmake;8;add_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;53;add_ompl_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;0;")
add_test(test_2dcircles_opt_geometric "/home/serboba/transferompl_ws/src/ompl_iso/demos/tests/test_2dcircles_opt_geometric")
set_tests_properties(test_2dcircles_opt_geometric PROPERTIES  _BACKTRACE_TRIPLES "/home/serboba/transferompl_ws/src/ompl_iso/CMakeModules/OMPLUtils.cmake;8;add_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;54;add_ompl_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;0;")
add_test(test_2dpath_simplifying "/home/serboba/transferompl_ws/src/ompl_iso/demos/tests/test_2dpath_simplifying")
set_tests_properties(test_2dpath_simplifying PROPERTIES  _BACKTRACE_TRIPLES "/home/serboba/transferompl_ws/src/ompl_iso/CMakeModules/OMPLUtils.cmake;8;add_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;55;add_ompl_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;0;")
add_test(test_constraint_sphere "/home/serboba/transferompl_ws/src/ompl_iso/demos/tests/test_constraint_sphere")
set_tests_properties(test_constraint_sphere PROPERTIES  _BACKTRACE_TRIPLES "/home/serboba/transferompl_ws/src/ompl_iso/CMakeModules/OMPLUtils.cmake;8;add_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;58;add_ompl_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;0;")
add_test(test_spacetime_STRRTstar "/home/serboba/transferompl_ws/src/ompl_iso/demos/tests/test_spacetime_STRRTstar")
set_tests_properties(test_spacetime_STRRTstar PROPERTIES  _BACKTRACE_TRIPLES "/home/serboba/transferompl_ws/src/ompl_iso/CMakeModules/OMPLUtils.cmake;8;add_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;61;add_ompl_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;0;")
add_test(test_2dmap_control "/home/serboba/transferompl_ws/src/ompl_iso/demos/tests/test_2dmap_control")
set_tests_properties(test_2dmap_control PROPERTIES  _BACKTRACE_TRIPLES "/home/serboba/transferompl_ws/src/ompl_iso/CMakeModules/OMPLUtils.cmake;8;add_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;64;add_ompl_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;0;")
add_test(test_planner_data_control "/home/serboba/transferompl_ws/src/ompl_iso/demos/tests/test_planner_data_control")
set_tests_properties(test_planner_data_control PROPERTIES  _BACKTRACE_TRIPLES "/home/serboba/transferompl_ws/src/ompl_iso/CMakeModules/OMPLUtils.cmake;8;add_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;65;add_ompl_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;0;")
add_test(test_experience_planning "/home/serboba/transferompl_ws/src/ompl_iso/demos/tests/test_experience_planning")
set_tests_properties(test_experience_planning PROPERTIES  _BACKTRACE_TRIPLES "/home/serboba/transferompl_ws/src/ompl_iso/CMakeModules/OMPLUtils.cmake;8;add_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;68;add_ompl_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;0;")
add_test(test_vamp_integration "/home/serboba/transferompl_ws/src/ompl_iso/demos/tests/test_vamp_integration")
set_tests_properties(test_vamp_integration PROPERTIES  _BACKTRACE_TRIPLES "/home/serboba/transferompl_ws/src/ompl_iso/CMakeModules/OMPLUtils.cmake;8;add_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;72;add_ompl_test;/home/serboba/transferompl_ws/src/ompl_iso/tests/CMakeLists.txt;0;")
subdirs("regression_tests")
